application:
  title: '@project.name@'
  version: '@project.version@'

book:
  name: "Sandra Parsick"
  age: "42"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always