application:
  title: '@project.name@'
  version: '@project.version@'

book:
  name: "Sandra Parsick"
  age: "42"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true